url: ""
baseurl: https://hackc0ders.github.io

# Site settings
title: HackCoders | Ethical Hacking & Programing
email: hackcoders01@gmail.com
description: "Comunidad dedicada para aprender y enseñar temas informáticos. Grupo de informáticos entusiastas que desean aportar un granito de arena a la comunidad"


# Team names, titles and social links

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
